Description: "This template interacts with the AwsCommunity::Lambda::Invoker hook, \nwhich is a single, central hook that invokes a series of Lambda functions\nto evaluate the compliance of stack operations. This template depends on \nthe AwsCommunity::DynamoDB::Item extension to be activated first. \n"

Resources:
  RegistrationTable:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::DynamoDB::Table
    Metadata:
      Comment: |
        This table holds a list of Lambda Arns that will be invoked by the
        AwsCommunity::Lambda::Invoker hook before CREATE, UPDATE, and DELETE
        operations.
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: lambda_arn
          AttributeType: S
      KeySchema:
        - AttributeName: lambda_arn
          KeyType: HASH

  BucketEncryptionCheck:
    Type: AWS::Lambda::Function
    Metadata:
      Comment: "This resource inherits from AWS::Lambda::Function to create the function and \nregister it with the DynamoDB table above. It makes a simple check to see \nif the BucketEncryption property is set, if the resource being checked is\nan AWS::S3::Bucket.\n"
    Properties:
      Runtime: python3.9
      Role: !GetAtt BucketEncryptionCheckLambdaRole.Arn
      Handler: index.handler
      Code:
        ZipFile: |
          import boto3
          def handler(event, context):
            print(event)
            if event["resource_name"] != "AWS::S3::Bucket":
              return
            if event["operation"] not in ["create", "update"]:
              return
            if "BucketEncryption" not in event["resource_properties"]:
              raise Exception("Expected BucketEncryption")

  BucketEncryptionCheckLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
      Path: /

  BucketEncryptionCheckRegistrationItem:
    Type: AwsCommunity::DynamoDB::Item
    Metadata:
      Comment: This resource puts an item into the registration table
    Properties:
      TableName: !Ref RegistrationTable
      Item:
        lambda_arn:
          S: !GetAtt BucketEncryptionCheck.Arn
      Keys:
        - AttributeName: lambda_arn
          AttributeType: S
          AttributeValue: !GetAtt BucketEncryptionCheck.Arn

  CheckWithDependencies:
    Type: AWS::Lambda::Function
    Metadata:
      Comment: "This resource inherits from AWS::Lambda::Function to create the function and \nregister it with the DynamoDB table above. This check demonstrates the ability \nto deploy a Python lambda function with dependencies.\n"
    Properties:
      Runtime: python3.9
      Role: !GetAtt CheckWithDependenciesLambdaRole.Arn
      Handler: index.handler
      Code:
        S3Bucket: rain-artifacts-755952356119-us-east-1
        S3Key: fd2aaca4e425740a873001d04d6120dcbd0a3c0083a28d68e214c4cbc6efc629

  CheckWithDependenciesLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
      Path: /

  CheckWithDependenciesRegistrationItem:
    Type: AwsCommunity::DynamoDB::Item
    Metadata:
      Comment: This resource puts an item into the registration table
    Properties:
      TableName: !Ref RegistrationTable
      Item:
        lambda_arn:
          S: !GetAtt CheckWithDependencies.Arn
      Keys:
        - AttributeName: lambda_arn
          AttributeType: S
          AttributeValue: !GetAtt CheckWithDependencies.Arn

Outputs:
  RegistrationTableArn:
    Value: !GetAtt RegistrationTable.Arn

