AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the AwsCommunity::S3::AccessControl resource type

Globals:
  Function:
    Timeout: 180  # docker start-up times can be long for SAM CLI
    MemorySize: 512

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.awscommunity.s3.accesscontrol.HookHandlerWrapper::handleRequest
      Runtime: java11
      CodeUri: ./target/awscommunity-s3-accesscontrol-handler-1.0-SNAPSHOT.jar

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.awscommunity.s3.accesscontrol.HookHandlerWrapper::testEntrypoint
      Runtime: java11
      CodeUri: ./target/awscommunity-s3-accesscontrol-handler-1.0-SNAPSHOT.jar
