version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo Entered the install phase...
      - echo About to build $MODULE_PATH
      - export PATH="/usr/local/bin:$PATH"
      - pip install git+https://github.com/aws-cloudformation/cloudformation-cli.git@master
      - pip install git+https://github.com/aws-cloudformation/cloudformation-cli-python-plugin.git@master
      - cd $MODULE_PATH
      - which python
      - python --version
      - ls /usr/local/bin
      - pip freeze
      - cfn --version
      - echo $PATH

  build:
    commands:
      - echo Entered the build phase...
      - cfn validate
      - cfn generate
      - SETUP_STACK_NAME="setup-$(echo $MODULE_PATH | sed s/modules\\///g | sed s/_/-/g)"
      - if test -e ./test/setup.yml; then rain deploy test/setup.yml $SETUP_STACK_NAME -y; fi
      - cfn submit --set-default
      - ./setup.sh
      - INTEG_STACK_NAME="integ-$(echo $MODULE_PATH | sed s/modules\\///g | sed s/_/-/g)"
      - rain deploy test/integ.yml $INTEG_STACK_NAME -y
    finally:
      - cat rpdk.log
      - if test -e ./test/setup.yml; then rain rm $SETUP_STACK_NAME -y; fi
      - rain rm $INTEG_STACK_NAME -y
      - ./cleanup.sh


