// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	AllowUsersToChangePassword *bool   `json:",omitempty"`
	HardExpiry                 *bool   `json:",omitempty"`
	MaxPasswordAge             *int    `json:",omitempty"`
	MinimumPasswordLength      *int    `json:",omitempty"`
	PasswordReusePrevention    *int    `json:",omitempty"`
	RequireLowercaseCharacters *bool   `json:",omitempty"`
	RequireNumbers             *bool   `json:",omitempty"`
	RequireSymbols             *bool   `json:",omitempty"`
	RequireUppercaseCharacters *bool   `json:",omitempty"`
	AccountId                  *string `json:",omitempty"`
}
