version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo Entered the install phase...
      - echo About to build $RESOURCE_PATH
      - ENTRY_PATH=$(python scripts/entry.py $RESOURCE_PATH/.rpdk-config)
      - echo ENTRY_PATH is $ENTRY_PATH
      - cd $RESOURCE_PATH
      - python -m venv .env
      - . .env/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install -r requirements-dev.txt
      - cfn --version
      - sam --version

  build:
    commands:
      - echo Entered the build phase...
      - cfn submit --set-default
      - INTEG_STACK_NAME="integ-$(echo $ENTRY_PATH | sed s/_/-/g)"
      - aws cloudformation create-stack --stack-name $INTEG_STACK_NAME --template-body file://test/integ.yml
      - aws cloudformation wait stack-create-complete --stack-name $INTEG_STACK_NAME
    finally:
      - cat rpdk.log
      - aws cloudformation delete-stack --stack-name $INTEG_STACK_NAME

