version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
      java: corretto8
    commands:
      - echo Entered the install phase...
      - echo About to build $RESOURCE_PATH
      - export PATH="/usr/local/bin:$PATH"
      - TYPE_NAME=$(python scripts/type_name.py $RESOURCE_PATH/.rpdk-config)
      - TYPE_CLEAN_NAME="$(echo $TYPE_NAME | sed s/::/-/g | tr ‘[:upper:]’ ‘[:lower:]’)"
      - echo TYPE_CLEAN_NAME is $TYPE_CLEAN_NAME
      - BUILD_FILE_NAME=$(cat TYPE_CLEAN_NAME | sed s/_/-/g)
      - BUILD_FILE_NAME="${BUILD_FILE_NAME}.zip"
      - pip install git+https://github.com/aws-cloudformation/cloudformation-cli-java-plugin.git@master
      - cd $RESOURCE_PATH
      - cfn --version
      - sam --version

  build:
    commands:
      - echo Entered the build phase...
      - cfn validate
      - cfn generate
      - ../../release/deregister-all.sh us-east-1 RESOURCE
      - mvn clean verify javadoc:javadoc
      - cfn submit --set-default
      - INTEG_STACK_NAME="integ-$(echo $TYPE_CLEAN_NAME | sed s/_/-/g)"
      - rain deploy test/integ.yml $INTEG_STACK_NAME -y
    finally:
      - cat rpdk.log
      - rain rm $INTEG_STACK_NAME -y

artifacts:
  files:
    - $BUILD_FILE_NAME
  name: extensions-build
