version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo Entered the install phase...
      - echo About to build $RESOURCE_PATH
      - export PATH="/usr/local/bin:$PATH"
      - /usr/local/bin/dockerd-entrypoint.sh
      - cat /var/log/docker.log
      - ENTRY_PATH=$(python scripts/entry.py $RESOURCE_PATH/.rpdk-config)
      - echo ENTRY_PATH is $ENTRY_PATH
      - BUILD_FILE_NAME=$(cat ENTRY_PATH | sed s/_/-/g)
      - BUILD_FILE_NAME="${BUILD_FILE_NAME}.zip"
      - pip install git+https://github.com/aws-cloudformation/cloudformation-cli-python-plugin.git@master
      - cd $RESOURCE_PATH
      - cfn --version
      - sam --version

  build:
    commands:
      - echo Entered the build phase...
      - cfn validate
      - cfn generate
      - cfn submit --set-default
      - INTEG_STACK_NAME="integ-$(echo $ENTRY_PATH | sed s/_/-/g)"
      - aws cloudformation create-stack --stack-name $INTEG_STACK_NAME --template-body file://test/integ.yml
      - aws cloudformation wait stack-create-complete --stack-name $INTEG_STACK_NAME
    finally:
      - cat rpdk.log
      - aws cloudformation delete-stack --stack-name $INTEG_STACK_NAME

artifacts:
  files:
    - $BUILD_FILE_NAME 
  name: extensions-build

