version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo Entered the install phase...
      - pwd
      - ls
      - echo About to build $RESOURCE_PATH
      - ENTRY_PATH=$(python resources/entry.py $RESOURCE_PATH/.rpdk-config)
      - echo ENTRY_PATH is $ENTRY_PATH
      - cd $RESOURCE_PATH
      - pip install -r requirements.txt
      - pip install -r src/requirements.txt
      - cfn --version
      - sam --version
      - ls /
      - ls /root
      - mkdir /root/.docker
      - echo "{ \"auths\": { \"https://index.docker.io/v1/\": {} } }" > /root/.docker/config.json

  build:
    commands:
      - echo Entered the build phase...
      - pylint src/$ENTRY_PATH
      - pytest src
      - cfn validate
      - cfn generate
      - cfn submit --dry-run
      - aws cloudformation create-stack --stack-name setup-$ENTRY_PATH --template-body file://test/setup.yml
      - sam local start-lambda &
      - cfn test
    finally:
      - cat rpdk.log
      - aws cloudformation delete-stack --stack-name setup-$ENTRY_PATH

