version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo Entered the install phase...
      - echo About to build $RESOURCE_PATH
      - ENTRY_PATH=$(python resources/entry.py $RESOURCE_PATH/.rpdk-config)
      - echo ENTRY_PATH is $ENTRY_PATH
      - cd $RESOURCE_PATH
      - python -m venv .env
      - . .env/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install -r src/requirements.txt
      - cfn --version
      - sam --version

  build:
    commands:
      - echo Entered the build phase...
      - pylint --rcfile .pylintrc src/$ENTRY_PATH
      - pytest src
      - cfn validate
      - cfn generate
      - SETUP_STACK_NAME="setup-$(echo $ENTRY_PATH | sed s/_/-/g)"
      - aws cloudformation create-stack --stack-name $SETUP_STACK_NAME --template-body file://test/setup.yml
      - aws cloudformation wait stack-create-complete --stack-name $SETUP_STACK_NAME
      - cfn submit --dry-run
      - nohup sam local start-lambda &
      - cfn test
    finally:
      - cat rpdk.log
      - aws cloudformation delete-stack --stack-name $SETUP_STACK_NAME

