version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo Entered the install phase...
      - echo About to build $RESOURCE_PATH
      - export PATH="/usr/local/bin:$PATH"
      - pip install git+https://github.com/aws-cloudformation/cloudformation-cli.git@master
      - pip install git+https://github.com/aws-cloudformation/cloudformation-cli-go-plugin.git@master
      - /usr/local/bin/dockerd-entrypoint.sh
      - cat /var/log/docker.log
      - TYPE_NAME=$(python scripts/type_name.py $RESOURCE_PATH/.rpdk-config)
      - echo TYPE_NAME is $TYPE_NAME
      - cd $RESOURCE_PATH
      - pwd
      - ls
      - aws --version
  build:
    commands:
      - echo Entered the build phase...
      - make  # For GO we need to build before cfn submit is run
      - ls -l ../../release
      - ../../release/publish-regions.sh
    finally:
      - cat rpdk.log
