version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo Entered the install phase...
      - echo About to build $RESOURCE_PATH
      - ENTRY_PATH=$(python scripts/entry.py $RESOURCE_PATH/.rpdk-config)
      - echo ENTRY_PATH is $ENTRY_PATH
      - TYPE_NAME=$(python scripts/type_name.py $RESOURCE_PATH/.rpdk-config)
      - echo TYPE_NAME is $TYPE_NAME
      - cd $RESOURCE_PATH

  build:
    commands:
      - echo Entered the build phase...
      - ./release/publish.sh
    finally:
      - cat rpdk.log

