name: Bug report
description: Create a report to help us improve an extension

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Try to include as much information as you can.
  - type: input
    attributes:
      label: Extension Name
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction template
      description: Provide the template used to reproduce this bug
      placeholder: |
        ```yaml
        AWSTemplateFormatVersion: "2010-09-09"
        ...
        ```
    validations:
      required: true
