name: Feature request
description: Suggest an idea for an extension (3rd party and custom resources, hooks, modules)

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a feature request! Try to include as much information as you can.

  - type: dropdown
    attributes:
      label: What type of extension are you looking for?
      description: Which type of extension in the CloudFormation registry is this for?
      multiple: true
      options:
        - Resource
        - Module
        - Hook
        - Other

  - type: textarea
    attributes:
      label: Describe the extension you'd like to request
      description: |
        A clear and concise description of the extension you would like to have. Please include **any related issues**, documentation, etc.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: |
        A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other use cases or context about the feature request here. Please include any prototype, workaround, reference implementation, etc.

  - type: checkboxes
    attributes:
      label: Is this something that you'd be interested in working on?
      options:
        - label: 👋 I may be able to implement this feature request

  - type: checkboxes
    attributes:
      label: Would this feature include a breaking change?
      options:
        - label: ⚠️ This feature might incur a breaking change
