blank_issues_enabled: true
contact_links:
  - name: I want help working with an AwsCommunity CloudFormation extension
    url: https://discord.gg/GCa2jC4GUe
    about: Check out the `Need Help?` channels on CloudFormation's community Discord
