AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the AwsCommunity::CloudTrail::LogValidationEnabled resource type

Globals:
  Function:
    Timeout: 180  # docker start-up times can be long for SAM CLI
    MemorySize: 256

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: awscommunity_cloudtrail_logvalidationenabled.handlers.hook
      Runtime: python3.9
      CodeUri: build/

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: awscommunity_cloudtrail_logvalidationenabled.handlers.test_entrypoint
      Runtime: python3.9
      CodeUri: build/

