// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	Id            *string  `json:",omitempty"`
	Seconds       *int     `json:",omitempty"`
	SleepOnCreate *bool    `json:",omitempty"`
	SleepOnUpdate *bool    `json:",omitempty"`
	SleepOnDelete *bool    `json:",omitempty"`
	Triggers      []string `json:",omitempty"`
}
