Parameters:
  Env:
    Type: String
    Description: The environment, cicd or beta
    AllowedValues: ["cicd", "beta"]
  BuildManagedPolicyArn:
    Type: String
    Description: The CodeBuild Managed Policy ARN
  FolderName:
    Type: String
    Description: The folder name for the hook
Conditions:
  IfCloudFrontWebAclAssociation: !Equals [!Ref FolderName, CloudFront_WebAclAssociation]
  IfBucketNotification: !Equals [!Ref FolderName, S3_BucketNotification]
  IfDeleteBucketContents: !Equals [!Ref FolderName, S3_DeleteBucketContents]
  IfIamPasswordPolicy: !Equals [!Ref FolderName, IAM_PasswordPolicy]
Resources:
  IamPasswordPolicyBuildProjectPolicy:
    Condition: IfIamPasswordPolicy
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - iam:GetRole
              - iam:CreateRole
              - iam:DeleteRole
              - s3:PutObject
              - s3:GetObject
              - s3:PutBucketWebsite
              - s3:GetEncryptionConfiguration
              - s3:ListAllMyBuckets
              - s3:PutBucketPolicy
              - s3:GetBucketLocation
              - s3:DeleteBucket
              - s3:CreateBucket
              - s3:ListBucket
              - s3:GetBucketPolicy
              - s3:PutBucketCORS
              - s3:DeleteBucketPolicy
            Effect: Allow
            Resource: "*"
        Version: '2012-10-17'
      PolicyName: cloudfront-webacl-association-build-project-policy
      Roles:
        - !Ref BuildProjectRole
  DeleteBucketContentsBuildProjectPolicy:
    Condition: IfDeleteBucketContents
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - iam:CreateRole
              - iam:DeleteRole
              - iam:GetRole
              - s3:CreateBucket
              - s3:DeleteBucket
              - s3:ListBucket
              - s3:GetBucketNotification
              - s3:PutBucketNotification
              - s3:GetBucketTagging
              - s3:PutBucketTagging
              - s3:ListObjectVersions
              - s3:DeleteObject
              - s3:ListBucketVersions
            Effect: Allow
            Resource: "*"
        Version: '2012-10-17'
      PolicyName: delete-bucket-contents-build-project-policy
      Roles:
        - !Ref BuildProjectRole
  BucketNotificationBuildProjectPolicy:
    Condition: IfBucketNotification
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - lambda:AddPermission
              - lambda:RemovePermission
              - s3:CreateBucket
              - s3:DeleteBucket
              - s3:GetBucketNotification
              - s3:PutBucketNotification
              - sns:AddPermission
              - sns:ConfirmSubscription
              - sns:CreateTopic
              - sns:DeleteTopic
              - sns:GetTopicAttributes
              - sns:RemovePermission
              - sns:SetTopicAttributes
              - sqs:CreateQueue
              - sqs:DeleteQueue
              - sqs:AddPermission
              - sqs:GetQueueAttributes
              - sqs:GetQueueUrl
              - sqs:SetQueueAttributes
            Effect: Allow
            Resource: "*"
        Version: '2012-10-17'
      PolicyName: bucket-notification-build-project-policy
      Roles:
        - !Ref BuildProjectRole
  CloudFrontWebAclAssociationBuildProjectPolicy:
    Condition: IfCloudFrontWebAclAssociation
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - iam:GetRole
              - iam:CreateRole
              - iam:DeleteRole
              - wafv2:ListTagsForResource
              - wafv2:GetWebACL
              - wafv2:CreateWebACL
              - wafv2:DeleteWebACL
              - cloudfront:ListCloudFrontOriginAccessIdentities
              - cloudfront:TagResource
              - cloudfront:CreateDistribution
              - cloudfront:GetDistribution
              - cloudfront:CreateCloudFrontOriginAccessIdentity
              - cloudfront:ListDistributions
              - cloudfront:GetCloudFrontOriginAccessIdentity
              - cloudfront:DeleteDistribution
              - cloudfront:UpdateDistribution
              - cloudfront:DeleteCloudFrontOriginAccessIdentity
              - s3:PutObject
              - s3:GetObject
              - s3:PutBucketWebsite
              - s3:GetEncryptionConfiguration
              - s3:ListAllMyBuckets
              - s3:PutBucketPolicy
              - s3:GetBucketLocation
              - s3:DeleteBucket
              - s3:CreateBucket
              - s3:ListBucket
              - s3:GetBucketPolicy
              - s3:PutBucketCORS
              - s3:DeleteBucketPolicy
            Effect: Allow
            Resource: "*"
        Version: '2012-10-17'
      PolicyName: cloudfront-webacl-association-build-project-policy
      Roles:
        - !Ref BuildProjectRole
  BuildProjectRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
        - !Ref BuildManagedPolicyArn
  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_LARGE
        Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/cep-cicd:latest"
        ImagePullCredentialsType: SERVICE_ROLE
        PrivilegedMode: true
        Type: LINUX_CONTAINER
        EnvironmentVariables:
        - Name: HOOK_PATH
          Type: PLAINTEXT
          Value: !Sub "./resources/${FolderName}"
      ServiceRole: !GetAtt BuildProjectRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub "hooks/${Env}-buildspec-python.yml"
Outputs:
  BuildProjectRole:
    Value: !Ref BuildProjectRole
  BuildProjectArn:
    Value: !GetAtt BuildProject.Arn
  BuildProjectName:
    Value: !Ref BuildProject
