AWSTemplateFormatVersion: "2010-09-09"
Description: Common infrastructure for the community registry extensions CICD in the prod account for publishing across all regions

Parameters:

  HandlerBucketName:
    Type: String
    Description: The name of the handler package bucket. For prod it should be community-registry-extensions-prod-handler

  PublishBuildBucketName:
    Type: String
    Description: The name of the bucket to drop builds from the beta account when all integ tests succeed. In prod it should be community-registry-extensions-publish-build

  BetaAccountId:
    Type: String
    Description: AccountId for the beta account, which pushes builds to the PublishBuildBucket 

Resources:

  PublishBuildBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PublishBuildBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: BetaAccountPut
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${BetaAccountId}:role/cep-publish-role" 
            Action: s3:PutObject
            Resource: 
              - !Sub "arn:aws:s3:::${PublishBuildBucket}" 
              - !Sub "arn:aws:s3:::${PublishBuildBucket}/*" 

  PublishBuildBucket:
    Type: AWS::S3::Bucket
    Metadata:
      Comment: This bucket initiates the publishing process in the prod account when a file called build.zip is dropped from the beta account
    Properties:
      BucketName: !Ref PublishBuildBucketName
      VersioningConfiguration: 
        Status: Enabled

  ArtifactBucket:
    Type: AWS::S3::Bucket

  HandlerBucket:
    Type: AWS::S3::Bucket
    Metadata:
      Comment: This bucket holds the handler package and logs for `release/publish.sh`
    Properties:
      BucketName: !Ref HandlerBucketName

  WebHookCloudWatchEventRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: community-registry-extensions-cloudwatch-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        -
          PolicyName: cwe-pipeline-execution
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action: codepipeline:StartPipelineExecution
                Resource: !Join [ '', [ 'arn:aws:codepipeline:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', "*" ] ]


  WebHookCloudTrailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebHookCloudTrailBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Sid: AWSCloudTrailAclCheck
            Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !GetAtt WebHookCloudTrailBucket.Arn
          -
            Sid: AWSCloudTrailWrite
            Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Join [ '', [ !GetAtt WebHookCloudTrailBucket.Arn, '/AWSLogs/', !Ref 'AWS::AccountId', '/*' ] ]
            Condition: 
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
  
  WebHookCloudTrailBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
  
  WebHookCloudTrail:
    DependsOn:
      - WebHookCloudTrailBucketPolicy
    Type: AWS::CloudTrail::Trail
    Properties:
      S3BucketName: !Ref WebHookCloudTrailBucket
      EventSelectors:
        -
          DataResources:
            -
              Type: AWS::S3::Object
              Values:
                - !Join [ '', [ !GetAtt PublishBuildBucket.Arn, '/', "build.zip" ] ]
          ReadWriteType: WriteOnly
          IncludeManagementEvents: false
      IncludeGlobalServiceEvents: true
      IsLogging: true
      IsMultiRegionTrail: true


