AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the AwsCommunity::Resource::Lookup resource type

Globals:
  Function:
    Timeout: 180  # docker start-up times can be long for SAM CLI
    MemorySize: 512

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.awscommunity.resource.lookup.HandlerWrapper::handleRequest
      Runtime: java8
      CodeUri: ./target/awscommunity-resource-lookup-handler-1.0-SNAPSHOT.jar

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.awscommunity.resource.lookup.HandlerWrapper::testEntrypoint
      Runtime: java8
      CodeUri: ./target/awscommunity-resource-lookup-handler-1.0-SNAPSHOT.jar
