// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	Id            *string  `json:",omitempty"`
	Time          *string  `json:",omitempty"`
	OffsetDays    *int     `json:",omitempty"`
	OffsetHours   *int     `json:",omitempty"`
	OffsetMinutes *int     `json:",omitempty"`
	OffsetMonths  *int     `json:",omitempty"`
	OffsetSeconds *int     `json:",omitempty"`
	OffsetYears   *int     `json:",omitempty"`
	Utc           *string  `json:",omitempty"`
	Day           *string  `json:",omitempty"`
	Hour          *string  `json:",omitempty"`
	Minute        *string  `json:",omitempty"`
	Month         *string  `json:",omitempty"`
	Second        *string  `json:",omitempty"`
	Unix          *string  `json:",omitempty"`
	Year          *string  `json:",omitempty"`
	Triggers      []string `json:",omitempty"`
}
